// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7379JxxvLDl_UuXPWqdX7_68ltnwZMGc',
    appId: '1:867632234448:web:f694da2ec17934361dc3d5',
    messagingSenderId: '867632234448',
    projectId: 'babyshophub-29d1d',
    authDomain: 'babyshophub-29d1d.firebaseapp.com',
    storageBucket: 'babyshophub-29d1d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZiYobhfZHqowLR1pe0_PZxfOv4t6q3MU',
    appId: '1:867632234448:android:f20bd089b2484d741dc3d5',
    messagingSenderId: '867632234448',
    projectId: 'babyshophub-29d1d',
    storageBucket: 'babyshophub-29d1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdutFelzkuBwJt_VeImuriOWweH0xfKX8',
    appId: '1:867632234448:ios:039a7f9978dc7fda1dc3d5',
    messagingSenderId: '867632234448',
    projectId: 'babyshophub-29d1d',
    storageBucket: 'babyshophub-29d1d.firebasestorage.app',
    iosBundleId: 'com.example.babyshopubAdminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdutFelzkuBwJt_VeImuriOWweH0xfKX8',
    appId: '1:867632234448:ios:039a7f9978dc7fda1dc3d5',
    messagingSenderId: '867632234448',
    projectId: 'babyshophub-29d1d',
    storageBucket: 'babyshophub-29d1d.firebasestorage.app',
    iosBundleId: 'com.example.babyshopubAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7379JxxvLDl_UuXPWqdX7_68ltnwZMGc',
    appId: '1:867632234448:web:011eb2c56aa4e08e1dc3d5',
    messagingSenderId: '867632234448',
    projectId: 'babyshophub-29d1d',
    authDomain: 'babyshophub-29d1d.firebaseapp.com',
    storageBucket: 'babyshophub-29d1d.firebasestorage.app',
  );
}